version: "3.9"
services:
  helloworld:
    image: "${npm_config_dockerregistry}/${npm_package_name}:${npm_package_version}-${GIT_COMMIT}"
    build:
        dockerfile: "infra/Dockerfile"
    ports:
      - "80:80"
