Parameters:
  Name:
    Description: An environment name that will used to tag resources resource names
    Type: String

  DomainName:
    Description: Domain Name
    Type: String

  HostedZoneName:
    Description: Hosted Zone Name
    Type: String

  ClusterSize:
    Description: Number of EC2 instances in the cluster
    Type: Number
    Default: 4

  InstanceType:
    Description: Instance type for EC2 instance in the cluster
    Type: String
    Default: t3.nano

  VPC:
    Description: VPC to create the cluster in
    Type: AWS::EC2::VPC::Id
  
  PublicSubnets:
    Description: Public subnets of the VPC the cluster will be created in
    Type: CommaDelimitedList

  PrivateSubnets:
    Description: Private subnets of the VPC the cluster will be created in
    Type: CommaDelimitedList

Resources:
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: security-groups.yaml
      Parameters:
        Name: !Ref Name
        VPC: !Ref VPC

  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: load-balancers.yaml
      Parameters:
        DomainName: !Ref DomainName
        HostedZoneName: !Ref HostedZoneName
        Name: !Ref AWS::StackName
        VPC: !Ref VPC
        Subnets: !Ref PublicSubnets
        SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ecs-cluster.yaml
      Parameters:
        Name: !Ref AWS::StackName
        InstanceType: !Ref InstanceType
        ClusterSize: !Ref ClusterSize
        VPC: !Ref VPC
        SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        Subnets: !Ref PrivateSubnets

  LifecycleHook:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lifecyclehook.yaml
      Parameters:
        Cluster: !GetAtt ECS.Outputs.Cluster
        ECSAutoScalingGroupName: !GetAtt ECS.Outputs.ECSAutoScalingGroupName

Outputs:
  Url:
    Description: The cluster endpoint URL
    Value: !Join ["", [!GetAtt ALB.Outputs.LoadBalancerUrl, "/"]]
  Cluster:
    Description: The cluster
    Value: !GetAtt ECS.Outputs.Cluster
  HTTPSListener:
    Description: The cluster listener
    Value: !GetAtt ALB.Outputs.HTTPSListener
  HTTPListener:
    Description: The cluster listener
    Value: !GetAtt ALB.Outputs.HTTPListener
  AutoScalingRole:
    Description: The cluster scaling role
    Value: !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
    