Parameters:
  DomainName:
    Description: Domain Name
    Type: String

  HostedZoneName:
    Description: Hosted Zone Name
    Type: String

  ClusterSize:
    Description: Number of EC2 instances in the cluster
    Type: Number
    Default: 4

  InstanceType:
    Description: Instance type for EC2 instances in the cluster
    Type: String
    Default: t3.nano

  ContainerImage:
    Description: Container image url
    Type: String
    Default: image:latest

  ContainerPort:
    Description: Port that the container exposes
    Type: Number
    Default: 80

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../modules/vpc.yaml
      Parameters:
        Name: !Ref AWS::StackName

  ElasticacheClusterSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties: 
      Description: !Sub Subnet group for ${AWS::StackName}
      SubnetIds: !Split [',', !GetAtt VPC.Outputs.PrivateSubnets]

  ElasticacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    DependsOn: VPC
    Properties:    
      Engine: redis
      CacheNodeType: cache.t2.micro
      NumCacheNodes: 1
      CacheSubnetGroupName: !Ref ElasticacheClusterSubnetGroup
      VpcSecurityGroupIds:
        - !GetAtt VPC.Outputs.DefaultSecurityGroup

  HelloWorldCluster:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPC
    Properties:
      TemplateURL: ../../modules/main.yaml
      Parameters:
        Name: !Ref AWS::StackName
        DomainName: !Ref DomainName
        HostedZoneName: !Ref HostedZoneName
        ClusterSize: !Ref ClusterSize
        InstanceType: !Ref InstanceType
        VPC: !GetAtt  VPC.Outputs.VPC
        PublicSubnets: !Split [',', !GetAtt VPC.Outputs.PublicSubnets]
        PrivateSubnets: !Split [',', !GetAtt VPC.Outputs.PrivateSubnets]

  HelloWorldService:
    Type: AWS::CloudFormation::Stack
    DependsOn: ElasticacheCluster
    Properties:
      TemplateURL: ../../modules/service.yaml
      Parameters:
        Name: !Ref AWS::StackName
        Env1Name: 'REDIS_ADDRESS'
        Env1Value: !GetAtt ElasticacheCluster.RedisEndpoint.Address
        Env2Name: 'REDIS_PORT'
        Env2Value: !GetAtt ElasticacheCluster.RedisEndpoint.Port
        ContainerName: helloworld
        ContainerImage: !Ref ContainerImage
        ContainerPort: !Ref ContainerPort
        VPC: !GetAtt VPC.Outputs.VPC
        Cluster: !GetAtt HelloWorldCluster.Outputs.Cluster
        DesiredCount: 2
        HTTPSListener: !GetAtt HelloWorldCluster.Outputs.HTTPSListener
        HTTPListener: !GetAtt HelloWorldCluster.Outputs.HTTPListener
        Path: /
        ECSServiceAutoScalingRoleARN: !GetAtt HelloWorldCluster.Outputs.AutoScalingRole

Outputs:
  Url:
    Description: The URL endpoint for the helloworld service
    Value: !GetAtt HelloWorldCluster.Outputs.Url
