# 2. Create an ECS task definition, an ECS cluster, and an ECS service.
#    For example, follow the Getting Started guide on the ECS console:
#      https://us-east-2.console.aws.amazon.com/ecs/home?region=us-east-2#/firstRun
#    Replace the values for `service` and `cluster` in the workflow below with your service and cluster names.
#
# 3. Store your ECS task definition as a JSON file in your repository.
#    The format should follow the output of `aws ecs register-task-definition --generate-cli-skeleton`.
#    Replace the value of `task-definition` in the workflow below with your JSON file's name.
#    Replace the value of `container-name` in the workflow below with the name of the container
#    in the `containerDefinitions` section of the task definition.

name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

  login:
    name: Login to Amazon ECR
    runs-on: ubuntu-latest
    environment: production

    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

  build:
    name: Build docker image
    runs-on: ubuntu-latest
    environment: production
    needs: login
    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:
    - name: Build docker image
      id: build-image
      env:
        GIT_COMMIT: ${{ github.sha }}
      run: |
        npm run docker_build --dockerregistry "${{ needs.login.outputs.registry }}" 
        echo "::set-output name=image::${{ needs.login.outputs.registry }}/helloworld:${{ github.sha }}"

  push:
    name: Push docker image to Amazon ECR
    runs-on: ubuntu-latest
    environment: production
    needs: login

    steps:
    - name: Push docker image to Amazon ECR
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        npm run docker_push --dockerregistry "${{ needs.login.outputs.registry }}" 

  deploy:
    name: Deploy to Amazone ECS service
    runs-on: ubuntu-latest
    environment: production
    needs: build

    steps:
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: infra/task-definition.json
        container-name: helloworld
        image: ${{ needs.build.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: prod-helloworld
        cluster: prod-1
        wait-for-service-stability: true
